# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c22e422d1e07599ccf6f56092e7e6e4f68302ef3c98ba8fb7215ccfd8c3cd0cde21792cb614cbe9925aad7fff4ead3d4283f6ff3aa46465d11979e90a8969453

test:
  secret_key_base: a3a9e9dc4cfc71ac53adbe5cc8249fca531a9581cf081c3ef305276a24356ad0141a048d2632e818abd70859e3e1cd60a3837cc87870079a2b0fc71853fd8c4b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
